# This is a basic workflow to help you get started with Actions
 
# name:
#   First Cron Job
 
  # Controls when the workflow will run
# on:
#   # Triggers the workflow every 5 minutes
# #   schedule:
# #     - cron: '0 5 * * 1-5'
 
#       # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "cron"
#   cron:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
 
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: npm run test
        
        
name:
  Lightbeam e2e Tests
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  e2e-Test-Cycle:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: e2e Tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run test || true
        continue-on-error: true
