# This is a basic workflow to help you get started with Actions
 
# name:
#   First Cron Job
 
  # Controls when the workflow will run
# on:
#   # Triggers the workflow every 5 minutes
# #   schedule:
# #     - cron: '0 5 * * 1-5'
 
#       # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "cron"
#   cron:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
 
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: npm run test
        
        
# name:
#   Lightbeam e2e Tests
# on: [push]
#   # Triggers the workflow every 5 minutes

    
# jobs:
#   e2e-Test-Cycle:
#     runs-on: macos-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: e2e Tests
#         uses: cypress-io/github-action@v2
#         with:
#           build: npm run test || true
#         continue-on-error: true

name: Lightbeam e2e Tests

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests
        run: npm run test

# jobs:
#   build:

#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14.x'
#     - run: npm install
#     - run: npm run test
#       working-directory: ./owasp_juice_shop/cypress_code/owasp_automation
